### ISSUE TITLE
How to download multiple files?

### ISSUE THREAD

**Issue by PepikVaio** [JBlocklove/remarkable-daily-pdf#9] opened 2023-12-10 12:58 UTC
I tried to edit the "download-pdf"

#!/bin/sh
cd remarkable-daily-pdf/
./rm-sync-pdf -u https://example1 -n "title1"
./rm-sync-pdf -u https://example2 -n "title2"

Only the latest pdf is always downloaded

I tried to edit the "rm-sync-pdf"
I deleted the reboot request, had a 2x download and then created a script with only reboot or did I reset manually.
But not a single file downloaded.

Thanks

**Comment by JBlocklove** [comment] 2023-12-10 14:29
Hm, if you're on a 3.* version of the remarkable OS then the `gnu-wget` that's packaged with this (originally from [toltec](https://github.com/toltec-dev/toltec)) doesn't work anymore, which might be the cause of this issue. I've been making some fixes/improvements since I updated recently which should resolve this problem.

For the time being, I'd recommend grabbing the `rm-sync-pdf` from the `dev` branch. It replaces `gnu-wget` with the built-in `wget` which means we can't currently support TSL but at least it'll download some sites. I also added a `-r` option which allows you to choose whether or not to reset `xochitl`. This way you can omit that in your `download-pdfs` script and then just add `systemctl restart xochitl` at the end of the script to do the refresh and have the files show up.

Hope this solves your problem. I'm hoping to do a fair bit of updating over the next month or so which should make this project a bit more robust and usable.

**Comment by JBlocklove** [comment] 2024-01-14 17:56
Just did a pretty major refactor of the functions for this project (some some future WIPs) that should resolve this issue and a number of others. The README instructions should still be accurate, though I'll be doing a full documentation update relatively soon.

If you get the chance, please let me know if the updates have resolved your issue

**Comment by JBlocklove** [comment] 2024-08-02 12:36
I believe this is resolved, so I'll be closing this issue. A future TODO is to make a function that will prompt for adding more pdfs, like the initial install script, but that likely won't be for a while.

**Closed as completed by JBlocklove** 2024-08-02 12:36 UTC
